run:
  tests: true

linters-settings:
  funlen:
    lines: 150
    statements: 80    
  depguard:
    rules:
      main:
        files:
          - $all         
        allow:
          - $gostd
          - github.com
          - gitlab.com
linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - depguard
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - funlen
    - gci
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagliatelle
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
        - gocyclo
        - gosec
    - path: internal/hmac/
      text: "weak cryptographic primitive"
      linters:
        - gosec


